--liquibase formatted sql

--changeset bootcamp team:insert-initial-data
--comment: Sequences and tables for users module

INSERT INTO AUTORES_GOOD(NAME) VALUES ('A3');
INSERT INTO AUTORES_GOOD(NAME) VALUES ('A2');

INSERT INTO LIBROS_GOOD(TITULO, AUTOR_ID) VALUES ('TITUILO1', (SELECT AUTOR_ID FROM AUTORES_GOOD WHERE NAME='A3'));
INSERT INTO LIBROS_GOOD(TITULO, AUTOR_ID) VALUES ('TITUILO2', (SELECT AUTOR_ID FROM AUTORES_GOOD WHERE NAME='A2'));